# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for all rules.
default: true
line-length: false
# first-line-heading/first-line-h1
# MD041: false
no-inline-html: false
# no-alt-text
# MD045: false
# link-fragments
# MD051: false
# no-emphasis-as-heading
# MD036: false
# heading-increment
# MD001: false
fenced-code-language: false
# MD040: false
# ol-prefix
# MD029: false
# no-trailing-punctuation
# MD026: false
# table-column-style - disabled as strict alignment is hard to maintain
table-column-style: false
